<?xml version="1.0"?>
<package format="3">
  <name>web_dyn_reconf</name>
  <version>0.0.0</version>
  <description>The web_dyn_reconf package</description>

  <author email="sam.pfeiffer@pal-robotics.com">Sammy Pfeiffer</author>
  <maintainer email="sam.pfeiffer@pal-robotics.com">Sammy Pfeiffer</maintainer>

  <license>BSD</license>

  <depend>rclpy</depend>
  <depend>rcl_interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>